services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27019:27017'
    volumes:
      - './mongo-data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express
    ports:
      - '8088:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://root:123456@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data: