services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27019:27017'
    volumes:
      - './mongo-data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6377:6379'
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data: